version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my_nkap
        container_name: my_nkap
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=my_nkap
            - DB_USERNAME=my_nkap
            - DB_PASSWORD=my_nkap
        ports:
            -   "8000:8000"

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    mysql:
        image: mysql:8.0.3
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_nkap
            MYSQL_USER: my_nkap
            MYSQL_PASSWORD: my_nkap
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql:
        driver: local
