services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my_nkap
        container_name: my_nkap
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=my_nkap
            - DB_USERNAME=my_nkap
            - DB_PASSWORD=my_nkap
        ports:
            - "8000:8000"
        command: >
            sh -c "composer install --ignore-platform-req=ext-http &&
                   php artisan key:generate &&
                   php artisan db:seed --class=ProfessionsSeed &&
                   php-fpm"
        deploy:
            resources:
                limits:
                    memory: '128M'

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "81:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    memory: '128M'

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_nkap
            MYSQL_USER: my_nkap
            MYSQL_PASSWORD: my_nkap
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "--silent" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    memory: '256M'

networks:
    app-network:
        driver: bridge

volumes:
    mysql:
        driver: local
